### ISSUE TITLE
SmbServerNameHardeningLevel policy has incorrect value

### ISSUE THREAD

**Issue by heatherdaye** [PowerShell/SecurityPolicyDsc#90]
SmbServerNameHardeningLevel policy has incorrect value which causes get-dscconfiguration to report NULL. This causes failure in Azure DSC. The value is set correctly in the Security Policy.

The setting “Accept if provided by the client” should be “Accept if provided by client” (no 'the').
The other two values "Off" and "Required from client" set and report correctly and do not fail in Azure DSC.

**Comment by johlju** [comment]
I agree that this is a bug. 
Documented as 'Accept if provided by client' both at [Microsoft network server: Server SPN target name validation level](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj852272%28v%3dws.11%29) and at [Microsoft network server: Server SPN target name validation level](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/microsoft-network-server-server-spn-target-name-validation-level).

Labeling this as 'Good first issue' and 'help wanted' so that anyone in the community can run with this.
